PND-Gamjakkang/PND-Server

src/main/java/com/server/pnd/classDiagram/service/ChatGPTService.java, src/main/java/com/server/pnd/classDiagram/service/DiagramServiceImpl.java, src/main/java/com/server/pnd/project/dto/ProjectCreatedResponseDto.java, src/main/java/com/server/pnd/project/service/ProjectServiceImpl.java
=> 🚨 [Fix] 프로젝트 생성 - fix response dto

src/main/java/com/server/pnd/classDiagram/service/ChatGPTService.java, src/main/java/com/server/pnd/classDiagram/service/DiagramServiceImpl.java, src/main/java/com/server/pnd/domain/ClassDiagram.java, src/main/java/com/server/pnd/test/controller/TestController.java, src/main/java/com/server/pnd/test/dto/ClassDiagramCreatedRequestDto.java, src/main/java/com/server/pnd/test/service/TestService.java, src/main/java/com/server/pnd/test/service/TestServiceImpl.java
- close #52 
프론트와의 통신을 위한 클래스다이어그램 생성 테스트 API
(1차 예선 동영상 촬영)
1. 201 성공 
2. 프로젝트 찾기 실패 (404)
(아이디 3을 가진 프로젝트 없음)
=> 🧪 [Test] 클래스다이어그램 생성 테스트 API

src/main/java/com/server/pnd/util/config/ChatGPTConfig.java
- close #55 
util>config>ChatGPTConfig.java 파일 추가
=> 🔧 ChatGPTConfig 파일 추가

src/main/java/com/server/pnd/test/service/TestServiceImpl.java
=> 📝 플로우차트 더미테이터 수정

src/main/java/com/server/pnd/classDiagram/gpt/config/ApplicationConfig.java, src/main/java/com/server/pnd/classDiagram/gpt/config/ChatGPTConfig.java, src/main/java/com/server/pnd/classDiagram/gpt/dto/ChatCompletionDto.java, src/main/java/com/server/pnd/classDiagram/gpt/dto/ChatRequestMsgDto.java
- close #
ChatRequestMsgDto 추가 및 config 파일 구조 재배치
=> 🎨 ChatRequestMsgDto 추가 및 config 파일 구조 재배치

src/main/java/com/server/pnd/classDiagram/gpt/dto/ChatCompletionDto.java
- close #
ChatCompletionDto 추가
=> 🎨 ChatCompletionDto 추가

src/main/java/com/server/pnd/domain/SequenceDiagram.java
domain 패키지에 시퀀스 다이어그램 엔티티 추가
- close #
domain 패키지에 시퀀스 다이어그램 엔티티 추가
=> 📝 Sequence Diagram 엔티티 추가

src/main/java/com/server/pnd/domain/Repo.java, src/main/java/com/server/pnd/readme/controller/ReadmeController.java, src/main/java/com/server/pnd/readme/repository/ReadmeRepository.java, src/main/java/com/server/pnd/readme/service/ReadmeService.java, src/main/java/com/server/pnd/readme/service/ReadmeServiceImpl.java, src/main/java/com/server/pnd/repo/service/RepoServiceImpl.java, src/main/java/com/server/pnd/test/dto/ClassDiagramCreatedRequestDto.java, src/main/java/com/server/pnd/test/service/TestServiceImpl.java, src/main/resources/application.properties
=> 🚨 [Fix] Repo, Readme 수정 관련 오 수정

src/main/java/com/server/pnd/diagram/service/DiagramService.java
엔티티 생성 예외 구조 추가. 중복 로직 리팩토링 필요
- close #78 
classScriptGpt가 null이거나 비어있다면, GPT API를 호출하여 새로 생성하는 로직 추가
노션 각 API 명세서 하단에 첨부
Diagram 관련 API 부분 中(https://www.notion.so/hyejinworkspace/API-e4fa4be966e348b08374ca2618df6895?pvs=4)
**Class Diagram**
**Sequence Diagram**
=> 🚨 시퀀스 다이어그램 GPT 생성 오류 해결

src/main/java/com/server/pnd/report/controller/ReportController.java, src/main/java/com/server/pnd/report/dto/EventInfoDto.java, src/main/java/com/server/pnd/report/dto/GitHubEvent.java, src/main/java/com/server/pnd/report/service/ReportService.java, src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
=> ✨[Feat] Github report API 구현 1 - 깃허브 api로 event 가져오기 & 이미지 생성 연습

src/main/resources/scripts/3d-contrib/src/index.ts
=> 🚨 [Fix] event 관련 오류 수정

src/main/resources/scripts/3d-contrib/src/aggregate-user-info.ts, src/main/resources/scripts/3d-contrib/src/file-writer.ts, src/main/resources/scripts/3d-contrib/src/index.ts
- close #86 
✨ [Feat] 깃허브 레포트 - 3D contrib 생성 구현 (깃허브 토큰 관련 수정 완료)
=> ✨ [Feat] 깃허브 레포트 - 3D contrib 생성 구현 (깃허브 토큰 관련 수정 완료)

build.gradle
=> ✨ [Deploy] test 코드 사용하지 않음

src/main/resources/scripts/3d-contrib/src/index.ts
- close #169 
report 생성 관련 log 추가
=> ✨ [Feat] Report 생성 log 추가

src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
- close #169 
ReportServiceImpl - file 로드 위치 수정
=> ✏️ [Fix] Report - File 로드 위치 수정(업로드,삭제) - ReportServiceImpl

src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
=> ✏️ [Fix] report log 추가

.github/workflows/aws.yml
=> [Deploy] CI/CD 완료 - Docker, Github Action을 이용한 CI/CD 구현 완료

src/main/java/com/server/pnd/readme/service/ReadmeServiceImpl.java
프롬프트 수정, 예시 3 추가
- close #
- prompt 내용 추가
- 예시 3 추가
=> 🎨 리드미 자동생성 API 프롬프트 수정

src/main/java/com/server/pnd/readme/service/ReadmeServiceImpl.java
- close #
: 헤더 fontAlign = 50으로 수정
@Jun-Young-Seo
=> 🩹 리드미 자동생성 API 프롬프트 수정

src/main/java/com/server/pnd/diagram/service/DiagramService.java
=> 📝 다이어그램 프롬프트 영어로 변경
